version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: paym8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      
    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: